export const CALL_API_USERS = '@USERS/CALLING_USERS_API';
export const CALL_API_USERS_SUCCESS = '@USERS/CALLED_USERS_API_SUCCESS';
export const CALL_API_USERS_FAILED = '@USERS/CALLED_USERS_API_FAILED';
